name: Test

on: push

jobs:

  better:
    name: better.com
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: better.com
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v2
      - run: go mod download
      - run: go vet ./...
      - run: go test ./...
